name: Continuous Integration Test Pipeline

on:
  # Pipeline akan otomatis berjalan setiap ada push ke branch 'main'
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Mengambil kode dari repository

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        # Menginstal PyTest dan pytest-html untuk pelaporan
        pip install pytest pytest-html

    - name: Run automated tests and generate report
      run: |
        # Menjalankan PyTest dan membuat laporan HTML
        pytest --html=laporan_hasil_uji.html --self-contained-html

    - name: Upload Test Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: laporan hasil uji # Nama artifact yang akan diunduh
        path: laporan_hasil_uji.html # File laporan yang diunggah
